[project]
name = 'Blockchain-Based-Smart-City-Adaptive-Governance'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.citizen-participation]
path = 'contracts/citizen-participation.clar'
clarity_version = 2
epoch = 2.5

[contracts.governance-entity-verification]
path = 'contracts/governance-entity-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
